### PR TITLE
add maven wrapper to simplify contributions

### PR DESCRIPTION
**Pull request by isopov**
Adding maven wrapper to project will alow to contribute without maven installed and will ensure that all contributors use single maven version.

### CODE REVIEW

**Comment by isopov** [comment]
@jeevatkm tried to fix travis in #100 - allowing failures on java9+ will make it green. Making it pass on both java8 and java9+ will require a bit of work on tests.

**Comment by jeevatkm** [comment]
@isopov Yes, I just saw that PR too. It seems Jmockito has an issue initializing it.

**Comment by jeevatkm** [comment]
@isopov BTW thought to clarify. Compiling and publishing to maven central using jdk8 would keep the library compatible with multiple JDK(s)? Your thoughts?

**Comment by isopov** [comment]
>Compiling and publishing to maven central using jdk8 would keep the library compatible with multiple JDK(s)?

Sure. Building with newer JDKs is only to keep project healthy and ease contributions (so that contributors should not install extra specific JDK just for that)

**Pull request merged**
