### PR TITLE
Support for LoadBalancer endpoint.

### PR DESCRIPTION
**Pull request by tlehoux**
I've added support for LoadBalancer endpoint API, in order to manage DigitalOcean Load Balancer feature.

### CODE REVIEW

**Comment by tlehoux** [comment]
@jeevatkm Just to be sure: do you want me to do this only for code I added or do you want me to do these changes for all the project ?

**Comment by jeevatkm** [comment]
@tlehoux I would like to know, Do you have time to accommodate these changes for all the project?

**Comment by tlehoux** [comment]
Sure, that's not a big deal. 

Except for 
_create isNull(Object o) and isNotNull(Object o) use across_
because I'm not sure how far do you want to go.

**Comment by jeevatkm** [comment]
That's fine, thank you for your help. I will do the null check after merging this PR.

**Comment by tlehoux** [comment]
No problem. I could add support for Firewall endpoint when I have a little more time.

**Comment by jeevatkm** [comment]
Thank you, sure I'm looking forward to your PR.

I'm merging this PR.

**Pull request merged**
